name: html_template
description: An HTML template engine based on String interpolation.
version: 0.0.1
homepage: https://github.com/xvrh/html_template

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.40.0
  build:
  dart_style:
  html: ^0.14.0
  meta: ^1.0.0
  source_gen:

dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers:
  pedantic: ^1.9.0
  test:
